apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.functionName }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: ${{ values.githubOrg }}/${{ values.functionName }}
  tags:
    - lambda
    - serverless
    - aws
spec:
  type: service
  lifecycle: production
  owner: user:guest
