apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.appName }}
  description: ${{ values.appName }} deployed on Kubernetes via Helm
  annotations:
    github.com/project-slug: ${{ values.githubOrg }}/${{ values.appName }}
    backstage.io/kubernetes-namespace: default
  tags:
    - kubernetes
    - helm
spec:
  type: service
  lifecycle: production
  owner: user:guest
